version: '3'
services:
  ecsdemo-frontend:
    image: amazon/amazon-ecs-sample
    ports:
      - "80:80"
    logging:
      driver: awslogs
      options: 
        awslogs-group: helloworld
        awslogs-region: $AWS_DEFAULT_REGION
        awslogs-stream-prefix: helloworld