version: '3'
services:
  ecsdemo-frontend:
    image: amazon/amazon-ecs-sample
    ports:
      - "3000:3000"
    logging:
      driver: awslogs
      options: 
        awslogs-group: ecsdemo-frontend
        awslogs-region: $AWS_DEFAULT_REGION
        awslogs-stream-prefix: ecsdemo-frontend