version: '3'
services:
  $AWS_RESOURCE_NAME_PREFIX:
    image: amazon/amazon-ecs-sample
    ports:
      - "80:80"
    logging:
      driver: awslogs
      options: 
        awslogs-group: $AWS_RESOURCE_NAME_PREFIX
        awslogs-region: $AWS_DEFAULT_REGION
        awslogs-stream-prefix: $AWS_RESOURCE_NAME_PREFIX