version: '3'
services:
  helloworld:
    # image: amazon/amazon-ecs-sample
    image: nginx:latest
    ports:
      - "3000:80"
    logging:
      driver: awslogs
      options: 
        awslogs-group: $AWS_RESOURCE_NAME_PREFIX
        awslogs-region: $AWS_DEFAULT_REGION
        awslogs-stream-prefix: $AWS_RESOURCE_NAME_PREFIX