version: 2.1
jobs:
  build:
    docker:
      - image: node:10-alpine
    steps:
      - checkout
      - run:
          name: Add Dependencies
          command: apk add --no-cache --update curl git python py-pip
      - run:
          name: Install & Build Helloworld
          command: npm install
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: test if else in circleci
          command: |
            set -e
            # LASTEST_COMMIT=$(git rev-parse HEAD)
            # BACKEND_COMMIT=$(git log -1 --format=format:%H --full-diff ./backend)
            # FRONTEND_COMMIT=$(git log -1 --format=format:%H --full-diff ./frontend)
            LASTEST_COMMIT=DEF
            BACKEND_COMMIT=ABC
            FRONTEND_COMMIT=DEF
            if [ $BACKEND_COMMIT = $LASTEST_COMMIT ];
                then
                  echo "Backend is latest commit"
            elif [ $FRONTEND_COMMIT = $LASTEST_COMMIT ];
                then
                  echo "Frontend is latest commit"
                  pwd
                  ls -a
                  chmod +x frontend-dev.sh
                  sh frontend-dev.sh
            else
                echo "no folder of latest commit"
                exit 0;
            fi
workflows:
  version: 2
  build-test-deploy:
    jobs:
      - build:
          filters:
            branches:
              only: master

          
