version: 2
jobs:
  build:
    docker:
      - image: node:10-alpine
    steps:
      - checkout
      - run:
          name: Add Dependencies
          command: apk add --no-cache --update curl git python py-pip
      - run:
          name: Install & Build Helloworld
          command: npm install
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Install Docker client
          command: |
            set -x
            VER="18.09.7"
            curl -L -o /tmp/docker-$VER.tgz https://download.docker.com/linux/static/stable/x86_64/docker-$VER.tgz
            tar -xz -C /tmp -f /tmp/docker-$VER.tgz
            mv /tmp/docker/* /usr/bin
      - run: 
          name: Setup Environments AWS-CLI
          command: |
            pip install awscli
            pip install --upgrade awscli
      - run:
          name: Setup configure AWS
          command: |
            aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
            aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
            aws configure set default.region $AWS_DEFAULT_REGION
      - run:
          name: Build & Push to ECR
          command: |
            $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)
            docker build -t helloworld .
            docker tag helloworld:latest 871468375256.dkr.ecr.ap-southeast-1.amazonaws.com/helloworld:latest
            docker push 871468375256.dkr.ecr.ap-southeast-1.amazonaws.com/helloworld:latest
workflows:
  version: 2
  build-test-deploy:
    jobs:
      - build:
          filters:
            branches:
              only: master

          