version: 2
jobs:
  build:
    machine: true 
    steps:
      - checkout
      - run:
          name: Install Docker client
          command: |
            set -x
            VER="18.09.7"
            curl -L -o /tmp/docker-$VER.tgz https://download.docker.com/linux/static/stable/x86_64/docker-$VER.tgz
            tar -xz -C /tmp -f /tmp/docker-$VER.tgz
            mv /tmp/docker/* /usr/bin
      - run: 
          name : Setup Environments AWS-CLI
          command: |
            cat /etc/os-release
workflows:
  version: 2
    build-test-deploy:
      jobs:
        - build:
            filters:
              branches:
                only: master

          